Screen:

    MDRectangleFlatButton:
        text: "Light Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        md_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Primary Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}


    MDRaisedButton:
        text: "Dark Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.3}
        md_bg_color: app.theme_cls.primary_dark